name:                html-haskell
version:             0.1.0.0
github:              "jundl77/html-haskell"
license:             BSD3
author:              "Julian Brendl"
maintainer:          "julianbrendl@gmail.com"
copyright:           "2019 Julian Brendl"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jundl77/html-haskell#readme>

dependencies:
- base >= 4.7 && < 5
- aeson

library:
  source-dirs: src
  dependencies:
  - html-haskell
  - type-of-html
  - aeson

executables:
  html-haskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - html-haskell
    - type-of-html
    - scotty
    - aeson

tests:
  html-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - html-haskell
